Repository FranAnillo/decide, pull requests merged in 2021-12, with the labels that each got.

#69 RECUENTO BORDA
  decide/postproc/views.py
Labels: enhancement

#67 Mayoria Absoluta
  decide/postproc/views.py
Labels: enhancement

#70 Tests Mayoria Absoluta
  decide/postproc/tests.py
Labels: enhancement

#68 Test recuento borda
  decide/postproc/tests.py
Labels: test

#71 Mayoria relativa
  decide/postproc/views.py
Labels: enhancement

#73 Creacion tests sustraccion
  decide/postproc/tests.py
  decide/postproc/views.py
Labels: test

#72 Creacion del metodo de sustraccion
  decide/postproc/views.py
Labels: enhancement

#75 Aplicar el algoritmo de Webster
  decide/postproc/views.py
Labels: enhancement

#74 Añadido algoritmo de Hamilton
  decide/postproc/views.py
Labels: enhancement

#77 Añadido pruebas de algoritmo de hamilton
  decide/postproc/tests.py
Labels: test

#76 Aplicar el algoritmo de Webster
  decide/postproc/views.py
Labels: enhancement

#79 Solucionados errores con recuento borda y mayoría absoluta
  decide/postproc/tests.py
  decide/postproc/views.py
Labels: bug, enhancement, test

#78 Añadidas pruebas de webster
  decide/postproc/tests.py
Labels: test
