Repository FranAnillo/decide, pull requests merged in 2022-01, with the labels that each got.

#101 Pruebas mayoria relativa
  decide/local_settings.example.py
  decide/postproc/tests.py
Labels: enhancement

#103 Implementado de django.yml
  .github/workflows/django.yml
Labels: enhancement

#107 Realizado la visualización general del postproc
  decide/voting/migrations/0004_voting_voting_type.py
  decide/voting/models.py
Labels: enhancement

#109 Visualizacion sustraccion
  decide/voting/models.py
Labels: enhancement

#108 Visualizacion mayoria relativa
  decide/voting/models.py
Labels: enhancement

#110 Implementación del método dhont en la visualización de votos
  decide/voting/models.py
Labels: enhancement

#116 115-Visualizacion Hamilton
  decide/voting/models.py
Labels: enhancement

#111 Visualización webster
  decide/voting/models.py
Labels: enhancement

#117 VISUALIZACION RECUENTO BORDA
  decide/voting/models.py
Labels: enhancement

#118 VISUALIZACION MAYORIA ABSOLUTA
  decide/voting/models.py
Labels: enhancement

#120 119-Solucion seats métodos postproc
  decide/voting/models.py
Labels: enhancement

#123 DESPLIEGUE DOCKER
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: enhancement

#125 Realizado despliegue en Vagrant
  vagrant/Vagrantfile
  vagrant/python.yml
Labels: enhancement

#127 Añadido los cambios al requirements para vagrant y heroku
  requirements.txt
Labels: bug

#135 124-Pruebas de carga
  loadtest/gen_census.py
  loadtest/locustfile.py
  loadtest/question_orders.json
  loadtest/questions.json
  loadtest/votings.json
Labels: test

#136 Mergeo de rama Equipo-2 a master
  decide/local_settings.example.py
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/voting/migrations/0004_voting_voting_type.py
  decide/voting/models.py
  loadtest/gen_census.py
  loadtest/locustfile.py
  loadtest/question_orders.json
  loadtest/questions.json
  loadtest/votings.json
Labels: enhancement
